BE-36, chore: edit bung table name
open-run/backend pull request #48
Opened 2024-06-17 13:45 UTC by sonjh919

# 설명
bung 테이블명 변경

연관된 이슈: #36

## 변경사항
32c60a02c0a82c6e1d93c46d84b3759ff9a535b6 : 테이블명 변경
before:
- tb_bung
- tb_users_bung

after:
- tb_bungs
- tb_users_bungs

### 변경의 종류 (여러 가지 선택 가능)

- [ ] 버그 수정
- [ ] 새로운 기능
- [ ] 대규모 변경
- [ ] 문서 업데이트
- [x] 기타 {{테이블명 변경}}

# Author 체크리스트

- [ ] 테스트를 통과했나요?
- [x] 컴파일 가능한가요?
- [x] PR 하기 전에 코드를 다시 한번 살펴보셨나요?
- [ ] 이해하기 힘든 부분에 주석을 달아 두셨나요?
- [ ] 바뀐 부분에 대해 문서화도 새로 하셨나요?
- [x] PR이 새로운 컴파일 경고를 추가하는지 확인하셨나요?
- [ ] 변경사항을 검증할 수 있는 테스트를 추가하고 실행하셨나요?

2024-06-18 01:26 UTC, DonHK-97 approved these changes
confirmed

2024-06-19 01:51 UTC, yjkellyjoo requested changes

2024-06-19 01:51 UTC, yjkellyjoo commented on src/main/resources/schema.sql
> +                                       after_run_description VARCHAR(4096)
DEFAULT NULL은 왜 빠지심?

2024-06-19 01:51 UTC, yjkellyjoo commented on src/main/resources/schema.sql
> +                                             participation_Status BOOLEAN NOT NULL,
`participation_Status` -> `participation_status`

2024-06-19 02:54 UTC, sonjh919 commented on src/main/resources/schema.sql
> +                                       after_run_description VARCHAR(4096)
533b6f5 수정 완료!

2024-06-19 02:54 UTC, sonjh919 commented on src/main/resources/schema.sql
> +                                             participation_Status BOOLEAN NOT NULL,
533b6f5 수정 완료!

2024-06-21 02:21 UTC, yjkellyjoo approved these changes

2024-06-21 02:49 UTC, merged